name: Push Nightly Tag

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push-nightly-tag:
    runs-on: ubuntu-latest

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Push Nightly Tag
        uses: thejeff77/action-push-tag@v1.0.0
        with:
          force: true
          tag: nightly
